### ISSUE TITLE
Baue Auswahlseite

### ISSUE THREAD

**Issue by LuciusSpiro** [LuciusSpiro/WerewolfGamemaster#4]
Style die Seite passend.

Füge einen Button "zur Übersicht" hinzu welche auf die Übersichtsseite linked

Erweitere den KartenSpeicherService um eine Funktion addKarte funktion die eine Karte in die NächstesSpiel liste hinzufügt.

Rufe beim Tap event auf ein Bild die AddKarte Funktion auf und füge damit diese Karte einmal hinzu.

Graue Hinzugefügte karten bis auf Werwolf und Bürger nach hinzufügen aus.

Baue ein Info symbol bei den Karten ein, die bei Klick die detailseite für diese karte öffnet.

Füge einen Neues spiel button hinzu auf der Seite ganz oben welches die Funktion resetSpiel des KartenspeicherService triggert

Baue die KartenSpeicherService funktion resetSpiel. Welches das NächstesSpiel array leert.

**Comment by Tybil** [comment]
Detailansicht hinzugefügt

**Comment by Tybil** [comment]
Plus minus Buttons hinzugefügt
